version: '3.8'

services:
  zookeeper1:
    image: zookeeper:3.7.0
    container_name: zookeeper-1
    networks:
      - kafka-cluster-network
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181 server.3=zookeeper-3:2888:3888;2181
  zookeeper2:
    image: zookeeper:3.7.0
    container_name: zookeeper-2
    networks:
      - kafka-cluster-network
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181 server.3=zookeeper-3:2888:3888;2181
  zookeeper3:
    image: zookeeper:3.7.0
    container_name: zookeeper-3
    networks:
      - kafka-cluster-network
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181 server.3=zookeeper-3:2888:3888;2181
  kafka1:
    image: wurstmeister/kafka:2.12-2.4.1
    container_name: kafka-1
    networks:
      - kafka-cluster-network
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1,zookeeper2,zookeeper3
      KAFKA_LISTENERS: PLAINTEXT://kafka-1:9092
  kafka2:
    image: wurstmeister/kafka:2.12-2.4.1
    container_name: kafka-2
    networks:
      - kafka-cluster-network
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1,zookeeper2,zookeeper3
      KAFKA_LISTENERS: PLAINTEXT://kafka-2:9092
  kafka3:
    image: wurstmeister/kafka:2.12-2.4.1
    container_name: kafka-3
    networks:
      - kafka-cluster-network
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1,zookeeper2,zookeeper3
      KAFKA_LISTENERS: PLAINTEXT://kafka-3:9092

networks:
  kafka-cluster-network:
